Haber.Web/Models/ExtraHaber.cs
namespace Haber.Web.Models
{
    public class ExtraHaber
    {
        public string HaberGorsel { get; set; }
        public string HaberBaslik { get; set; }
        public string HaberKaynak { get; set; }
        public string HaberKategori { get; set; }
        public string HaberBaslikSeo { get; set; }
        public string HaberMetaBaslik { get; set; }
        public string HaberEklenme { get; set; }
        public int HaberOkunma { get; set; }
        public int HaberOkunmaSuresi { get; set; }
        public string HaberLink { get; set; }
        public string HaberMetaKisaBaslik { get; set; }
    }
}

Haber.Web/Controllers/DefaultController.cs
using Haber.Business;
using Haber.Web.Models;
using System.Collections.Generic;
using System.Web.Mvc;

namespace Haber.Web.Controllers
{
    public class DefaultController : Controller
    {
        //[OutputCache(Duration = 300)]
        public ActionResult index(string kaynak, string kategori)
        {
            var data = new List<Business.Haber>();
            HaberService HS = new HaberService();

            if (!string.IsNullOrEmpty(kategori) && !string.IsNullOrEmpty(kaynak))
            {
                data = HS.listMain(kategori, kaynak, 90);
                ViewBag.URL = "http://www.pandahaber.com/" + kaynak + "/" + kategori;
                ViewBag.Title = "Panda Haber | Panda'dan al haberi !";
                ViewBag.Description = "Panda Haber | " + kaynak + " sitesinden " + kategori + " haberleri gösteriliyor.";
            }
            else if (string.IsNullOrEmpty(kategori) && !string.IsNullOrEmpty(kaynak))
            {
                data = HS.listMain("", kaynak, 90);
                ViewBag.URL = "http://www.pandahaber.com/" + kaynak;
                ViewBag.Title = "Panda Haber | Panda'dan al haberi !";
                ViewBag.Description = "Panda Haber | " + kaynak + " sitesinden haberler gösteriliyor.";
            }
            else if (!string.IsNullOrEmpty(kategori) && string.IsNullOrEmpty(kaynak))
            {
                data = HS.listMain(kategori, "", 90);
                ViewBag.URL = "http://www.pandahaber.com/tumu/" + kategori;
                ViewBag.Title = "Panda Haber | Panda'dan al haberi !";
                ViewBag.Description = "Panda Haber | " + kategori + " haberleri gösteriliyor.";
            }
            else
            {
                data = HS.listMain("", "", 90);
                ViewBag.URL = "http://www.pandahaber.com/";
                ViewBag.Title = "Panda Haber | Panda'dan al haberi !";
                ViewBag.Description = "Panda Haber | Tüm haberler gösteriliyor.";
            }

            return View(data);
        }

        [OutputCache(Duration = 300, VaryByParam = "*")]
        public ActionResult akis(string kaynak, string kategori)
        {
            var data = new List<Business.Haber>();
            HaberService HS = new HaberService();
            data = HS.listForTimeline(kategori, kaynak);
            if (data.Count == 0 || data == null)
            {
                return RedirectToAction("index", "default");
            }

            if (!string.IsNullOrEmpty(kaynak) && !string.IsNullOrEmpty(kategori))
            {
                ViewBag.Title = "Panda Haber | Panda'dan al haberi !";
                ViewBag.Description = "Panda Haber | Haber Akışı";
                ViewBag.URL = "http://www.pandahaber.com/akis/" + kaynak + "/" + kategori;
            }
            else if (!string.IsNullOrEmpty(kaynak) && string.IsNullOrEmpty(kategori))
            {
                ViewBag.Title = "Panda Haber | Panda'dan al haberi !";
                ViewBag.Description = "Panda Haber | Haber Akışı";
                ViewBag.URL = "http://www.pandahaber.com/akis/" + kaynak;
            }
            else if (string.IsNullOrEmpty(kaynak) && !string.IsNullOrEmpty(kategori))
            {
                ViewBag.Title = "Panda Haber | Panda'dan al haberi !";
                ViewBag.Description = "Panda Haber | Haber Akışı";
                ViewBag.URL = "http://www.pandahaber.com/akis/tumu/" + kategori;
            }
            else
            {
                ViewBag.Title = "Panda Haber | Panda'dan al haberi !";
                ViewBag.Description = "Panda Haber | Haber Akışı";
                ViewBag.URL = "http://www.pandahaber.com/akis/" + kaynak + "/" + kategori;
            }

            return View(data);
        }

        [OutputCache(Duration = 3600, VaryByParam = "*")]
        public ActionResult haber(string kaynak, string kategori, string baslik)
        {
            var data = new Business.Haber();
            HaberService HS = new HaberService();
            data = HS.detail(kaynak, kategori, baslik);
            if (data == null || data.HaberID == 0)
            {
                return RedirectToAction("index", "default");
            }

            ViewBag.Title = "Panda Haber | Panda'dan al haberi !";
            ViewBag.Description = "Panda Haber | " + data.HaberBaslik;
            ViewBag.URL = "http://www.pandahaber.com/haber/" + kaynak + "/" + kategori + "/" + baslik;
            ViewBag.URL2 = "pandahaber.com/haber/" + kaynak + "/" + kategori + "/" + baslik;
            return View(data);
        }

        [HttpPost]
        public JsonResult getir(string kaynak, string kategori, int say)
        {
            List<ExtraHaber> haberler = new List<ExtraHaber>();
            HaberService HS = new HaberService();
            var data = HS.addList(kategori, kaynak, say);

            foreach (var item in data)
            {
                haberler.Add(new ExtraHaber
                {
                    HaberBaslik = item.HaberBaslik,
                    HaberBaslikSeo = item.HaberBaslikSeo,
                    HaberEklenme = item.HaberEklenme.ToString(),
                    HaberGorsel = item.HaberGorsel,
                    HaberKategori = item.HaberKategori,
                    HaberKaynak = item.HaberKaynak,
                    HaberMetaBaslik = item.HaberMetaBaslik,
                    HaberOkunma = item.HaberOkunma,
                    HaberOkunmaSuresi = item.HaberOkunmaSuresi,
                    HaberLink = item.HaberLink,
                    HaberMetaKisaBaslik = item.HaberMetaKisaBaslik
                });
            }

            return Json(haberler);
        }
    }
}

Haber.Web/Controllers/PartialController.cs
using Haber.Business;
using System.Web.Mvc;

namespace Haber.Web.Controllers
{
    public class PartialController : Controller
    {
        public ActionResult menu()
        {
            HaberService HS = new HaberService();
            var data = HS.menu();
            return View("_menu", data);
        }

        public ActionResult nav()
        {
            HaberService HS = new HaberService();
            var data = HS.menu();
            return View("_nav", data);
        }

        [OutputCache(Duration = 300)]
        public ActionResult header()
        {
            return View("_header");
        }

        [OutputCache(Duration = 300)]
        public ActionResult footer()
        {
            HaberService HS = new HaberService();
            var data = HS.menu();
            return View("_footer");
        }
    }
}

Haber.Web/Views/Default/akis.cshtml
@model List<Haber.Business.Haber>
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="tr">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="robots" content="index,follow">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Panda Haber | Panda'dan al haberi !</title>
    <meta name="keywords" content="panda haber, panda, haber">
    <meta name="description" content="">
    <meta name="copyright" content="Her hakkı saklıdır">
    <meta name="reply-to" content="iletisim@huseyinkayakiran.com">
    <meta name="author" content="Hüseyin Kayakıran">
    <meta name="application-name" content="Panda Haber | pandahaber.com">
    <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" />
    <link rel="canonical" href="@ViewBag.URL" />

    <meta property="og:title" content="@ViewBag.Title" />
    <meta property="og:type" content="article" />
    <meta property="og:image" content="http://pandahaber.com/facebook.jpg" />
    <meta property="og:url" content="@ViewBag.URL" />
    <meta property="og:description" content="@ViewBag.Description" />

    <meta name="twitter:card" content="summary" />
    <meta name="twitter:title" content="@ViewBag.Title" />
    <meta name="twitter:description" content="@ViewBag.Description" />
    <meta name="twitter:image" content="http://pandahaber.com/twittter.jpg" />

    @Styles.Render("~/bundles/style")

    <!--[if lt IE 9 ]>
    <script src="/~/Assets/Theme/assets/js/separate-js/html5shiv-3.7.2.min.js" type="text/javascript"></script><meta content="no" http-equiv="imagetoolbar">
    <![endif]-->
</head>
<body>
    <div id="page-preloader"><span class="spinner border-t_second_b border-t_prim_a"></span></div>
    <div class="l-theme animated-css" data-header="sticky" data-header-top="200" data-canvas="container">
        @Html.Action("header", "Partial")
        <div class="container">
            <div class="row">
                <div class="col-xs-12">
                    <div class="row">
                        <h2>Usage example</h2>
                        <div class="timeline timeline-line-dotted">
                            <span class="timeline-label">
                                <span class="label label-primary">17.03.2016</span>
                            </span>
                            @foreach (var item in Model)
                            {
                                <div class="timeline-item" id="@item.HaberID">
                                    <div class="timeline-point">
                                        <img src="@item.HaberGorsel" width="24" height="24" class="timeline-point-img" />
                                    </div>
                                    <div class="timeline-event">
                                        <div class="timeline-heading">
                                            <p>@item.HaberKaynak @item.HaberKategori @item.HaberEklenme</p>
                                            <h4><a href="/haber/@item.HaberKaynak/@item.HaberKategori/@item.HaberBaslikSeo"></a>@(item.HaberBaslik.Length >= 150 ? item.HaberBaslik.Substring(0, 150) + "..." : item.HaberBaslik)</h4>
                                        </div>
                                        <div class="timeline-body">
                                            <p>@item.HaberIcerik</p>
                                        </div>
                                        @*<div class="timeline-footer">

                                        </div>*@
                                    </div>
                                </div>
                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>
        @Html.Action("footer", "Partial")
    </div>
    @Scripts.Render("~/bundles/script")
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-109606885-1"></script>
    <script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-109606885-1');
    </script>
</body>
</html>

Haber.Web/Views/Default/haber.cshtml
@model Haber.Business.Haber
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="tr">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="robots" content="index,follow">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Panda Haber | Panda'dan al haberi !</title>
    <meta name="keywords" content="panda haber, panda, haber">
    <meta name="description" content="@Model.HaberBaslik">
    <meta name="copyright" content="Her hakkı saklıdır">
    <meta name="reply-to" content="iletisim@huseyinkayakiran.com">
    <meta name="author" content="Hüseyin Kayakıran">
    <meta name="application-name" content="Panda Haber | pandahaber.com">
    <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" />
    <link rel="canonical" href="@ViewBag.URL" />

    <meta property="og:title" content="@ViewBag.Title" />
    <meta property="og:type" content="article" />
    <meta property="og:image" content="http://pandahaber.com/facebook.jpg" />
    <meta property="og:url" content="@ViewBag.URL" />
    <meta property="og:description" content="@ViewBag.Description" />

    <meta name="twitter:card" content="summary" />
    <meta name="twitter:title" content="@ViewBag.Title" />
    <meta name="twitter:description" content="@ViewBag.Description" />
    <meta name="twitter:image" content="http://pandahaber.com/twittter.jpg" />

    @Styles.Render("~/bundles/style")

    <!--[if lt IE 9 ]>
    <script src="/~/Assets/Theme/assets/js/separate-js/html5shiv-3.7.2.min.js" type="text/javascript"></script><meta content="no" http-equiv="imagetoolbar">
    <![endif]-->
</head>
<body>
    <div id="page-preloader"><span class="spinner border-t_second_b border-t_prim_a"></span></div>
    <div class="l-theme animated-css" data-header="sticky" data-header-top="200" data-canvas="container">
        @Html.Action("header", "Partial")
        <div class="container">
            <div class="row">
                <div class="col-xs-12">
                    <ol class="breadcrumb">
                        <li><a href="/">Anasayfa</a></li>
                        <li><a href="/@Model.HaberKaynak">@Model.HaberKaynak</a></li>
                        <li><a href="/@Model.HaberKaynak/@Model.HaberKategori">@Model.HaberKategori</a></li>
                        <li class="active">@Model.HaberMetaKisaBaslik</li>
                    </ol>
                </div>
            </div>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="l-main-content l-main-content_mrg-right_minus">
                        <article class="b-post b-post-full clearfix">
                            <div class="entry-main">
                                <div class="entry-header">
                                    <h1 class="entry-title">@Model.HaberBaslik</h1>
                                </div>
                                <div class="entry-content">
                                    <img class="img-responsive" src="@Model.HaberGorsel" alt="@Model.HaberBaslik" />
                                    @Model.HaberIcerik
                                </div>
                                <div class="entry-footer">
                                    <div class="entry-footer__social">
                                        <span class="entry-footer__title">Paylaş</span>
                                        <ul class="social-net list-inline">
                                            <li class="social-net__item"><a class="social-net__link text-primary_h" href="https://www.facebook.com/sharer/sharer.php?u=@ViewBag.URL" target="_blank"><i class="icon fa fa-facebook"></i></a></li>
                                            <li class="social-net__item"><a class="social-net__link text-primary_h" href="https://twitter.com/home?status=@ViewBag.URL" target="_blank"><i class="icon fa fa-twitter"></i></a></li>
                                            <li class="social-net__item"><a class="social-net__link text-primary_h" href="https://plus.google.com/share?url=@ViewBag.URL" target="_blank"><i class="icon fa fa-google-plus"></i></a></li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </article>
                    </div>
                </div>
                <div class="col-md-12">
                    <div id="disqus_thread"></div>
                </div>
            </div>
        </div>
        @Html.Action("footer", "Partial")
    </div>
    @Scripts.Render("~/bundles/script")
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-109606885-1"></script>
    <script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-109606885-1');
    </script>
    <script>

        function guid() {
            function s4() {
                return Math.floor((1 + Math.random()) * 0x10000)
                  .toString(16)
                  .substring(1);
            }
            return s4() + s4() + '-' + s4() + '-' + s4() + '-' +
              s4() + '-' + s4() + s4() + s4();
        }

var disqus_config = function () {
    this.page.url = @ViewBag.URL2;
    this.page.identifier = guid();
};
(function() {
var d = document, s = d.createElement('script');
s.src = 'https://hbrhsynkykrn.disqus.com/embed.js';
s.setAttribute('data-timestamp', +new Date());
(d.head || d.body).appendChild(s);
})();
    </script>
    <noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>

</body>
</html>

Haber.Web/Views/Default/index.cshtml
@model List<Haber.Business.Haber>
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="tr">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="robots" content="index,follow">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@ViewBag.Title</title>
    <meta name="keywords" content="panda haber, panda, haber">
    <meta name="description" content="@ViewBag.Description">
    <meta name="copyright" content="Her hakkı saklıdır">
    <meta name="reply-to" content="iletisim@huseyinkayakiran.com">
    <meta name="author" content="Hüseyin Kayakıran">
    <meta name="application-name" content="Panda Haber | pandahaber.com">
    <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" />
    <link rel="canonical" href="@ViewBag.URL" />

    <meta property="og:title" content="@ViewBag.Title" />
    <meta property="og:type" content="article" />
    <meta property="og:image" content="http://pandahaber.com/facebook.jpg" />
    <meta property="og:url" content="@ViewBag.URL" />
    <meta property="og:description" content="@ViewBag.Description" />

    <meta name="twitter:card" content="summary" />
    <meta name="twitter:title" content="@ViewBag.Title" />
    <meta name="twitter:description" content="@ViewBag.Description" />
    <meta name="twitter:image" content="http://pandahaber.com/twittter.jpg" />

    @Styles.Render("~/bundles/style")

    <!--[if lt IE 9 ]>
    <script src="/~/Assets/Theme/assets/js/separate-js/html5shiv-3.7.2.min.js" type="text/javascript"></script><meta content="no" http-equiv="imagetoolbar">
    <![endif]-->
</head>
<body>
    <div id="page-preloader"><span class="spinner border-t_second_b border-t_prim_a"></span></div>
    <div class="l-theme animated-css" data-header="sticky" data-header-top="200" data-canvas="container">
        @Html.Action("header", "Partial")
        <div class="section-type-10 bg-grey-2">
            <div class="container-fluid">
                <div class="section-sm-top wrap-inl-bl">
                    <div class="row" id="haberArea">
                        @foreach (var item in Model)
                        {
                            <div class="col-lg-3 col-md-6 col-sm-6 col-xs-12">
                                <section class="b-post b-post_img-left b-post_img-140 clearfix">
                                    <div class="entry-media"><a class="js-zoom-images img-hover-effect" href="/haber/@item.HaberKaynak/@item.HaberKategori/@item.HaberBaslikSeo"><img class="img-responsive img-border-sm hov-scal" src="@item.HaberGorsel" alt="@item.HaberMetaKisaBaslik" /></a></div>
                                    <div class="entry-main">
                                        <div class="entry-header">
                                            <h2 class="entry-title"><a href="/haber/@item.HaberKaynak/@item.HaberKategori/@item.HaberBaslikSeo">@item.HaberMetaKisaBaslik</a></h2>
                                            <div class="entry-meta">
                                                <span class="entry-meta__item"><i class="icon fa fa-info text-primary"></i><a class="entry-meta__link" href="/haber/@item.HaberKaynak/@item.HaberKategori/@item.HaberBaslikSeo" title="Kaynak">@item.HaberKaynak , @item.HaberKategori , @item.HaberEklenme</a></span><br />
                                                <span class="entry-meta__item"><i class="icon fa fa-street-view text-primary"></i><a class="entry-meta__link" href="/haber/@item.HaberKaynak/@item.HaberKategori/@item.HaberBaslikSeo" title="Hit">@item.HaberOkunma</a></span>
                                                <span class="entry-meta__item"><i class="icon fa fa-hourglass-end text-primary"></i><a class="entry-meta__link" href="/haber/@item.HaberKaynak/@item.HaberKategori/@item.HaberBaslikSeo" title="Okunma Süresi">@item.HaberOkunmaSuresi</a></span><br />
                                                <span class="entry-meta__item"><i class="icon fa fa-link text-primary"></i><a class="entry-meta__link" href="@item.HaberLink?r=pandahaber.com" title="@item.HaberKaynak Kaynağından Oku" target="_blank">Kaynağından Oku</a></span>
                                            </div>
                                        </div>
                                    </div>
                                </section>
                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>
        @Html.Action("footer", "Partial")
    </div>
    @Scripts.Render("~/bundles/script")
    @*<script type="text/javascript">
        $(document).ready(function () {
            var say = 90;
            setInterval(function () {
                haberGetir(say);
                say = say + 30;
            }, 5000);

        });
        function haberGetir(fsay) {
            var fields = window.location.href.split('/');
            var s = fields[3];
            var c = fields[4];
            $.ajax({
                type: "POST",
                url: "/getir",
                data: "{'kaynak':'" + s + "','kategori':'" + c + "','say':'" + fsay + "'}",
                contentType: "application/json; charset=utf-8",
                dataType: "json",
                success: function (data) {
                    var count = Object.keys(data).length;
                    if (count > 0) {
                        $("#haberArea").append("<div class='col-md-12' id='loadingNew' style='width:100%; background-color:#fff; height: 40px;'><center><img src='/loading.gif' style='width: 180px; height: 40px; display:block;' /></center></div>");
                        setTimeout(() => {
                            $("#loadingNew").remove()
                            $('#haberArea').append("<div class='col-md-12' style='width:100%; background-color:#000; height: 25px;'><center><img src='/scroll.png' style='width: 25px; height: 25px; display:block;' /></center></div>");
                            $.each(data, function (index, obj) {
                                $('#haberArea').append("<div class='col-lg-3 col-md-6 col-sm-6 col-xs-12'><section class='b-post b-post_img-left b-post_img-140 clearfix'><div class='entry-media'><a class='js-zoom-images img-hover-effect' href=/haber/" + obj.HaberKaynak + "/" + obj.HaberKategori + "/" + obj.HaberBaslikSeo + "'><img class='img-responsive img-border-sm hov-scal' src=" + obj.HaberGorsel + " alt=" + obj.HaberMetaKisaBaslik + "/></a></div><div class='entry-main'><div class='entry-header'><h2 class='entry-title'><a href='/haber/" + obj.HaberKaynak + "/" + obj.HaberKategori + "/" + obj.HaberBaslikSeo + "'>" + obj.HaberMetaKisaBaslik + "</a></h2><div class='entry-meta'><span class='entry-meta__item'><i class='icon fa fa-info text-primary'></i><a class='entry-meta__link' href='/haber/" + obj.HaberKaynak + '/' + obj.HaberKategori + '/' + obj.HaberBaslikSeo + "' title='Kaynak'>" + obj.HaberKaynak + "," + obj.HaberKategori + "," + obj.HaberEklenme + "</a></span><span class='entry-meta__item'><i class='icon fa fa-street-view text-primary'></i><a class='entry-meta__link' href='/haber/" + obj.HaberKaynak + '/' + obj.HaberKategori + '/' + obj.HaberBaslikSeo + "' title='Hit'>" + obj.HaberOkunma + "</a></span><span class='entry-meta__item'><i class='icon fa fa-hourglass-end text-primary'></i><a class='entry-meta__link' href='/haber/" + obj.HaberKaynak + '/' + obj.HaberKategori + '/' + obj.HaberBaslikSeo + "' title='Okunma Süresi'>" + obj.HaberOkunmaSuresi + "</a></span><br /><span class='entry-meta__item'><i class='icon fa fa-link text-primary'></i><a class='entry-meta__link' href='" + obj.HaberLink + "?r=pandabahaber.com' + ' title='" + obj.HaberKaynak + " Kaynağından Oku' target='_blank'>Kaynağından Oku</a></span></div></div></div></section></div>");
                            });

                        }, 3000);
                    }
                }
            });
        }
    </script>*@
    <script type="text/javascript">
            $(document).ready(function () {
                haberGetir(90);
            });
            function haberGetir(fsay) {
                var fields = window.location.href.split('/');
                var s = fields[3];
                var c = fields[4];
                $.ajax({
                    type: "POST",
                    url: "/getir",
                    data: "{'kaynak':'" + s + "','kategori':'" + c + "','say':'" + fsay + "'}",
                    contentType: "application/json; charset=utf-8",
                    dataType: "json",
                    success: function (data) {
                        var count = Object.keys(data).length;
                        if (count > 0) {
                            $("#haberArea").append("<div class='col-md-12' id='loadingNew' style='width:100%; background-color:#fff; height: 40px;'><center><img src='/loading.gif' style='width: 180px; height: 40px; display:block;' /></center></div>");
                            setTimeout(() => {
                                $("#loadingNew").remove()
                                $('#haberArea').append("<div class='col-md-12' style='width:100%; background-color:#000; height: 25px;'><center><img src='/scroll.png' style='width: 25px; height: 25px; display:block;' /></center></div>");
                                $.each(data, function (index, obj) {
                                    $('#haberArea').append("<div class='col-lg-3 col-md-6 col-sm-6 col-xs-12'><section class='b-post b-post_img-left b-post_img-140 clearfix'><div class='entry-media'><a class='js-zoom-images img-hover-effect' href=/haber/" + obj.HaberKaynak + "/" + obj.HaberKategori + "/" + obj.HaberBaslikSeo + "'><img class='img-responsive img-border-sm hov-scal' src=" + obj.HaberGorsel + " alt=" + obj.HaberMetaKisaBaslik + "/></a></div><div class='entry-main'><div class='entry-header'><h2 class='entry-title'><a href='/haber/" + obj.HaberKaynak + "/" + obj.HaberKategori + "/" + obj.HaberBaslikSeo + "'>" + obj.HaberMetaKisaBaslik + "</a></h2><div class='entry-meta'><span class='entry-meta__item'><i class='icon fa fa-info text-primary'></i><a class='entry-meta__link' href='/haber/" + obj.HaberKaynak + '/' + obj.HaberKategori + '/' + obj.HaberBaslikSeo + "' title='Kaynak'>" + obj.HaberKaynak + "," + obj.HaberKategori + "," + obj.HaberEklenme + "</a></span><span class='entry-meta__item'><i class='icon fa fa-street-view text-primary'></i><a class='entry-meta__link' href='/haber/" + obj.HaberKaynak + '/' + obj.HaberKategori + '/' + obj.HaberBaslikSeo + "' title='Hit'>" + obj.HaberOkunma + "</a></span><span class='entry-meta__item'><i class='icon fa fa-hourglass-end text-primary'></i><a class='entry-meta__link' href='/haber/" + obj.HaberKaynak + '/' + obj.HaberKategori + '/' + obj.HaberBaslikSeo + "' title='Okunma Süresi'>" + obj.HaberOkunmaSuresi + "</a></span><br /><span class='entry-meta__item'><i class='icon fa fa-link text-primary'></i><a class='entry-meta__link' href='" + obj.HaberLink + "?r=pandabahaber.com' + ' title='" + obj.HaberKaynak + " Kaynağından Oku' target='_blank'>Kaynağından Oku</a></span></div></div></div></section></div>");
                                });

                            }, 3000);

                            setInterval(function () {
                                haberGetir(fsay + 30);
                            }, 5000);
                        }
                    }
                });
            }
        </script>
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-109606885-1"></script>
    <script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-109606885-1');
    </script>

</body>
</html>

Haber.Web/Views/Partial/_header.cshtml
<div class="wrap-fixed-menu" id="fixedMenu">
    <nav class="fullscreen-center-menu">
        <div class="menu-main-menu-container">
            <div class="slidebar-nav-menu">
                <nav>
                    @Html.Action("menu", "Partial")
                </nav>
            </div>

        </div>
    </nav>
    <button type="button" class="fullmenu-close"><i class="fa fa-times"></i></button>
</div>

<header class="header header-boxed-width header-logo-black header-navbar-white header-topbarbox-1-left header-topbarbox-2-right header-navibox-1-left header-navibox-3-right header-navibox-4-right navbar-fixed-top">
    <div class="container container-boxed-width">
        <div class="container-fluid">
            <div class="header-navibox-3">
                <ul class="nav navbar-nav hidden-xs clearfix vcenter">
                    <li>
                        <button class="js-toggle-screen toggle-menu-button"><i class="toggle-menu-button-icon"><span></span><span></span><span></span><span></span><span></span><span></span></i></button>
                    </li>
                </ul>
            </div>
            <div class="header-navibox-1">
                <button class="menu-mobile-button visible-xs-block js-toggle-screen toggle-menu-button"><i class="toggle-menu-button-icon"><span></span><span></span><span></span><span></span><span></span><span></span></i></button>
                <a class="navbar-brand scroll" href="/"><img class="normal-logo img-responsive" src="~/Assets/Theme/logo-dark.png" alt="logo" /><img class="scroll-logo img-responsive hidden-xs" src="~/Assets/Theme/logo-dark.png" alt="logo" /></a>
            </div>
        </div>
        <nav class="navbar" id="nav">
            <div class="container-fluid">
                <div class="header-navibox-2">
                    @Html.Action("nav", "Partial")
                </div>
            </div>
        </nav>
    </div>
</header>